#+TITLE:	README for format-errors
#+AUTHOR:	Renee Klawitter
#+EMAIL:	deepestthought42{monkey}gmail.com
#+DATE:		2016-05-03
#+STARTUP:	content


* What's this?
A small Common Lisp library to output value and errors in a way that
appeals to me and is used in the field I currently work in.


* Documentation
Usage should be as straightfoward as it gets. See documentation for details.
#+BEGIN_SRC lisp :results silent
(ql:quickload :format-errors)
(with-open-file (stream "README.md" :direction :output
                                    :if-exists :supersede)
  (describe format-errors:@format-errors-manual stream))
#+END_SRC



* Release history 
| version | comments               | date       |
|---------+------------------------+------------|
|   1.0.0 | initial public release | 2016/05/03 |


* COPYING
Copyright (c) 2016 R. Klawitter


Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


